site_name: excelsi
site_description: "Main documentation for excelsi project"
repo_url: https://github.com/xgeeks-geekathon/excelsi.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
